"""Add models

Revision ID: 505e5b2d3fdf
Revises: 
Create Date: 2025-08-02 08:34:49.438319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505e5b2d3fdf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
